# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

# Enforce consistent formatting on save with RuboCop
Layout/IndentationWidth:
  Enabled: true

Layout/FirstArgumentIndentation:
  Enabled: true

Layout/ArgumentAlignment:
  Enabled: true

Layout/LineLength:
  Enabled: true
  Max: 100
